[phases.setup]
nixPkgs = ['nodejs', 'npm', 'nmap', 'whois', 'dnsutils', 'curl']

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = ['echo "Installing security tools and configuring environment"']

[start]
cmd = 'cd backend && npm start'
